import React, { useEffect, useState, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { api, setToken } from './api';
import './styles.css';

type Project = { _id: string; name: string; webhookUrl: string };
type Job = { _id: string; name: string; status: string; priority: number; attempts: number; runAttempts: number; generation: number; createdAt: string; durationMs?: number; latencyMs?: number; payload?: unknown; error?: { code: string; message: string } };
type Key = { _id: string; name: string; prefix: string; revokedAt?: string };
type Delivery = { _id: string; eventId: string; url: string; status: string; attempts: number; logs: { attempt: number; statusCode: number; code: string; at: string }[] };
type Metrics = { collectedAt: string; rows: { _id: string; count: number; retried: number; avgDurationMs?: number; avgLatencyMs?: number }[]; hourly: { _id: string; count: number }[] };
const tabs = ['Overview', 'Jobs', 'API keys', 'Webhooks', 'Documentation'] as const;
const statusLabel = (s: string) => s === 'dead-letter' ? 'Dead letter' : s.charAt(0).toUpperCase() + s.slice(1);
const date = (v: string) => new Date(v).toLocaleString();

function App() {
  const [signedIn, setSignedIn] = useState(false), [checking, setChecking] = useState(true), [register, setRegister] = useState(false);
  const [projects, setProjects] = useState<Project[]>([]), [selected, setSelected] = useState(''), [tab, setTab] = useState<typeof tabs[number]>('Overview');
  const [jobs, setJobs] = useState<Job[]>([]), [keys, setKeys] = useState<Key[]>([]), [deliveries, setDeliveries] = useState<Delivery[]>([]), [metrics, setMetrics] = useState<Metrics | null>(null);
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [page, setPage] = useState(1), [total, setTotal] = useState(0), [status, setStatus] = useState('');
  const [modal, setModal] = useState<''|'project'|'event'|'key'|'detail'>(''), [detail, setDetail] = useState<Job | null>(null), [suggestion, setSuggestion] = useState(''), [revealed, setRevealed] = useState('');
  const project = projects.find(p => p._id === selected);
  async function loadProjects() {
    const data = await api<{ projects: Project[] }>('/projects');
    setProjects(data.projects); setSelected(current => data.projects.some(p => p._id === current) ? current : data.projects[0]?._id || '');
  }
  useEffect(() => { api<{ accessToken: string }>('/auth/refresh', { method: 'POST' }).then(r => { setToken(r.accessToken); setSignedIn(true); }).catch(() => {}).finally(() => setChecking(false)); }, []);
  useEffect(() => { if (signedIn) loadProjects().catch(e => setError(e.message)); }, [signedIn]);
  useEffect(() => {
    if (!selected || !signedIn) return;
    let cancelled = false;
    const load = async () => {
      try {
        const [j, m, k, d] = await Promise.all([
          api<{ jobs: Job[]; total: number }>(`/projects/${selected}/jobs?page=${page}${status ? `&status=${status}` : ''}`),
          api<Metrics>(`/projects/${selected}/metrics`), api<{ keys: Key[] }>(`/projects/${selected}/keys`), api<{ deliveries: Delivery[] }>(`/projects/${selected}/deliveries`),
        ]);
        if (!cancelled) { setJobs(j.jobs); setTotal(j.total); setMetrics(m); setKeys(k.keys); setDeliveries(d.deliveries); setError(''); }
      } catch (e) { if (!cancelled) setError((e as Error).message); }
    };
    void load(); const timer = setInterval(load, 10000); return () => { cancelled = true; clearInterval(timer); };
  }, [selected, signedIn, page, status, notice]);
  async function action(work: () => Promise<void>) { setBusy(true); setError(''); try { await work(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  function open(name: typeof modal) { setError(''); setRevealed(''); setSuggestion(''); setModal(name); }
  const rows = metrics?.rows || [], count = rows.reduce((s, r) => s + r.count, 0), succeeded = rows.find(r => r._id === 'succeeded');
  const failed = rows.find(r => r._id === 'dead-letter')?.count || 0, retried = rows.reduce((s, r) => s + r.retried, 0);
  if (checking) return <div className="auth"><p>Opening your workspace…</p></div>;
  if (!signedIn) return <div className="auth"><div className="auth-brand"><span className="mark">✦</span> eventforge</div><form className="auth-card" onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); void action(async () => { const r = await api<{ accessToken: string }>(`/auth/${register ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify({ email: form.get('email'), password: form.get('password') }) }); setToken(r.accessToken); setSignedIn(true); }); }}><div className="eyebrow">DEVELOPER WORKSPACE</div><h1>{register ? 'Build your event pipeline.' : 'Welcome back.'}</h1><p>Inspect every event. Understand every retry.</p><label>Email<input name="email" type="email" autoComplete="email" required placeholder="you@company.dev"/></label><label>Password<input name="password" type="password" minLength={12} maxLength={128} required autoComplete={register ? 'new-password' : 'current-password'}/></label><small>Use at least 12 characters.</small>{error && <p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy}>{busy ? 'Please wait…' : register ? 'Create account' : 'Sign in'}</button><button type="button" className="text-button" onClick={() => { setRegister(!register); setError(''); }}>{register ? 'Already have an account? Sign in' : 'New to EventForge? Create an account'}</button></form><p className="auth-foot">Reliable processing starts with visible state.</p></div>;
  return <div className="shell"><aside><div className="brand"><span className="mark">✦</span> eventforge</div><label className="project-label">PROJECT<select value={selected} onChange={e => { setSelected(e.target.value); setPage(1); setStatus(''); setMetrics(null); setJobs([]); setKeys([]); setDeliveries([]); }}>{!projects.length && <option value="">No projects yet</option>}{projects.map(p => <option key={p._id} value={p._id}>{p.name}</option>)}</select></label><button className="text-button new-project" onClick={() => open('project')}>＋ Create project</button><div className="nav-label">WORKSPACE</div><nav>{tabs.map((t, i) => <button className={tab === t ? 'nav active' : 'nav'} key={t} onClick={() => { setTab(t); setPage(1); setStatus(''); }}><span>{['◫','≋','⌘','↗','☷'][i]}</span>{t}</button>)}</nav><div className="sidebar-bottom"><div className="environment"><i/> Project-isolated workspace</div><button className="text-button" onClick={() => void action(async () => { await api('/auth/logout', { method: 'POST' }); setToken(''); setSignedIn(false); setSelected(''); setProjects([]); setJobs([]); setMetrics(null); setKeys([]); setDeliveries([]); setDetail(null); setRevealed(''); setModal(''); setNotice(''); })}>Sign out ↗</button></div></aside><main><header><span>{project?.name || 'Workspace'} <b>/</b> {tab}</span><button className="primary" disabled={!project} onClick={() => open('event')}>＋ Send event</button></header><div className="content">{error && <div role="alert" className="error">{error}</div>}{notice && <div role="status" className="notice">{notice}<button aria-label="Dismiss notification" onClick={() => setNotice('')}>×</button></div>}<div className="page-title"><div><div className="eyebrow">EVENT OPERATIONS</div><h1>{tab === 'Overview' ? 'Your pipeline, in focus.' : tab}</h1><p>{tab === 'Overview' ? 'Processing activity for events received in the last 24 hours.' : project?.name || 'Create a project to begin.'}</p></div>{metrics && <span className="updated">Updated {new Date(metrics.collectedAt).toLocaleTimeString()}</span>}</div>
  {!project && tab !== 'Documentation' ? <div className="empty panel"><span className="empty-symbol">✦</span><h2>Your first event starts here.</h2><p>Create a project, issue an API key, and send an event.</p><button className="primary" onClick={() => open('project')}>Create your first project</button></div> : <>
  {tab === 'Overview' && <><section className="metrics">{[['Events received',count.toLocaleString(),'Accepted into durable storage'],['Succeeded',(succeeded?.count || 0).toLocaleString(),'Completed processing'],['Average processing',succeeded?.avgDurationMs == null ? '—' : `${Math.round(succeeded.avgDurationMs)} ms`,'Measured successful attempts'],['Failure rate',count ? `${(failed / count * 100).toFixed(2)}%` : '—','Permanently failed / received'],['Average latency',succeeded?.avgLatencyMs == null ? '—' : `${Math.round(succeeded.avgLatencyMs)} ms`,'Intake through successful completion'],['Retry rate',count ? `${(retried / count * 100).toFixed(2)}%` : '—','Events with multiple attempts']].map(([label,value,sub]) => <div className="metric" key={label}><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>)}</section><section className="columns"><div className="panel"><h2>Event intake</h2><p className="muted">Events per hour · UTC · last 24 hours</p><div className="bars">{Array.from({length:24}, (_,i) => { const hour = new Date(); hour.setUTCMinutes(0,0,0); hour.setUTCHours(hour.getUTCHours() - 23 + i); const n = metrics?.hourly.find(h => h._id === hour.toISOString().replace('.000',''))?.count || 0; const max = Math.max(1,...(metrics?.hourly.map(h=>h.count)||[])); return <div key={i} title={`${hour.toISOString()}: ${n} events`} className="bar-slot"><div style={{height:`${n/max*100}%`, minHeight:n ? 3 : 0}}/></div>; })}</div><div className="chart-caption"><span>24 hours ago</span><span>Now</span></div>{!count && <p className="muted">No events recorded in this window.</p>}</div><div className="panel"><h2>Processing states</h2><p className="muted">Same 24-hour cohort</p>{['queued','running','retrying','succeeded','dead-letter'].map(s => <div className="state-row" key={s}><Status value={s}/><strong>{rows.find(r=>r._id===s)?.count || 0}</strong></div>)}<div className="retry-note">{retried} events with more than one attempt</div></div></section></>}
  {(tab === 'Overview' || tab === 'Jobs') && <section className="panel table-panel"><div className="table-heading"><h2>{tab === 'Overview' ? 'Recent jobs' : 'All jobs'}</h2><select aria-label="Filter job status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All states</option>{['queued','running','retrying','succeeded','dead-letter'].map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select></div><div className="table-scroll"><table><thead><tr><th>Event / job ID</th><th>State</th><th>Attempts</th><th>Processing</th><th>Received</th><th/></tr></thead><tbody>{jobs.map(j=><tr key={j._id}><td><b>{j.name}</b><code>{j._id}</code></td><td><Status value={j.status}/></td><td>{j.attempts}</td><td>{j.durationMs == null ? '—' : `${j.durationMs} ms`}</td><td>{date(j.createdAt)}</td><td><button className="text-button" onClick={()=>void action(async()=>{ const data = await api<{job:Job}>(`/projects/${selected}/jobs/${j._id}`); setDetail(data.job);open('detail'); })}>Inspect →</button></td></tr>)}</tbody></table></div>{!jobs.length && <div className="empty compact">No jobs match this view. Send an event to start processing.</div>}<div className="pagination"><span>{total} jobs</span><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page}</span><button disabled={page*25>=total} onClick={()=>setPage(page+1)}>Next</button></div></section>}
  {tab === 'API keys' && <section className="panel"><div className="table-heading"><div><h2>Project API keys</h2><p className="muted">Secrets are shown once. Revocation takes effect for new requests.</p></div><button className="primary" onClick={()=>open('key')}>Create key</button></div>{keys.map(k=><div className="key-row" key={k._id}><div><b>{k.name}</b><code>{k.prefix}…</code></div><span>{k.revokedAt ? 'Revoked' : 'Active'}</span><button disabled={!!k.revokedAt || busy} onClick={()=>void action(async()=>{await api(`/projects/${selected}/keys/${k._id}`,{method:'DELETE'});setNotice(`Key ${k.name} revoked.`);})}>Revoke</button></div>)}{!keys.length && <p className="empty compact">Create an API key to authenticate event requests.</p>}</section>}
  {tab === 'Webhooks' && <><section className="panel"><h2>Delivery endpoint</h2><p className="muted">Successful events are delivered with an HMAC signature and up to three attempts.</p><form key={selected+project?.webhookUrl} className="inline-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(async()=>{const r=await api<{signingSecret:string}>(`/projects/${selected}/webhook`,{method:'PUT',body:JSON.stringify({url:f.get('url')})});setRevealed(r.signingSecret);setNotice('Webhook configuration saved. Applies to new events.');await loadProjects();});}}><label>Public HTTPS endpoint<input name="url" defaultValue={project?.webhookUrl} placeholder="https://your-app.example/webhooks"/></label><button className="primary" disabled={busy}>Save endpoint</button></form><small>Leave empty to disable delivery for new events.</small>{revealed && <div className="secret"><b>Signing secret</b><code>{revealed}</code><button onClick={()=>setRevealed('')}>Hide</button></div>}</section><section className="panel"><h2>Delivery history</h2>{deliveries.map(d=><details key={d._id} className="delivery"><summary><code>{d.eventId}</code> <Status value={d.status}/> <span>{d.attempts} attempts</span></summary><p>{d.url}</p>{d.logs.map((l,i)=><p className="mono" key={i}>Attempt {l.attempt} · {l.statusCode || 'No HTTP response'} · {l.code} · {date(l.at)}</p>)}</details>)}{!deliveries.length && <p className="empty compact">No webhook deliveries recorded.</p>}</section></>}
  {tab === 'Documentation' && <section className="panel docs"><h2>Send your first event</h2><p>Create a project and an API key, then send JSON to the event endpoint. Reuse an idempotency key only for the same logical request.</p><pre>{`curl http://localhost:3001/events \\\n  -H 'content-type: application/json' \\\n  -H 'x-api-key: YOUR_PROJECT_KEY' \\\n  -H 'idempotency-key: order-123' \\\n  -d '{"name":"order.created","payload":{"orderId":"123"},"priority":8}'`}</pre><h2>Processing and retries</h2><p>Priority 10 is highest. Events get three attempts with exponential backoff. Exhausted events enter the dead-letter queue; use Inspect → Retry after addressing the failure.</p><p>The reference processor accepts validated events. For demos, payload <code>{'{"simulateFailure":true}'}</code> fails permanently, while <code>{'{"failUntilAttempt":1}'}</code> succeeds on its second attempt.</p><h2>Webhook verification</h2><p>Verify HMAC-SHA256 of <code>timestamp + "." + rawBody</code> with the signing secret. Headers are <code>x-eventforge-timestamp</code>, <code>x-eventforge-signature</code>, and <code>x-eventforge-id</code>. Reject old timestamps and deduplicate delivery IDs. Delivery is at least once.</p><h2>AI suggestions</h2><p>Only structured failure codes and attempt counts are sent to Gemini when you request a suggestion. Event payloads and raw logs are excluded. Suggestions are not confirmed root causes.</p></section>}
  </>}</div></main>
  {modal && <div className="backdrop"><Dialog label={modal === 'detail' ? 'Job details' : `Create ${modal}`} close={() => { setModal(''); setRevealed(''); }}><button className="close" aria-label="Close dialog" onClick={()=>{setModal('');setRevealed('');}}>×</button>{error && <p className="error" role="alert">{error}</p>}
  {modal === 'project' && <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(async()=>{const r=await api<{project:Project}>('/projects',{method:'POST',body:JSON.stringify({name:f.get('name')})});await loadProjects();setSelected(r.project._id);setModal('');setNotice('Project created. Create an API key next.');setTab('API keys');});}}><h2>Create a project</h2><label>Project name<input autoFocus name="name" required minLength={2} maxLength={80} placeholder="Commerce production"/></label><button className="primary" disabled={busy}>Create project</button></form>}
  {modal === 'key' && <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(async()=>{const r=await api<{secret:string}>(`/projects/${selected}/keys`,{method:'POST',body:JSON.stringify({name:f.get('name')})});setRevealed(r.secret);setNotice('API key created. Copy the secret before closing.');});}}><h2>Create an API key</h2>{revealed ? <div className="secret"><p>Copy this key now. It cannot be retrieved again.</p><code>{revealed}</code><button type="button" onClick={()=>void action(async()=>{await navigator.clipboard.writeText(revealed);setNotice('Key copied.');})}>Copy key</button></div> : <><label>Key name<input autoFocus name="name" required maxLength={80} placeholder="Development"/></label><button className="primary" disabled={busy}>Create key</button></>}</form>}
  {modal === 'event' && <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(async()=>{const payload=JSON.parse(String(f.get('payload')));const ik=String(f.get('idempotency'));const r=await api<{jobId:string;duplicate:boolean}>('/events',{method:'POST',headers:{'x-api-key':String(f.get('key')),...(ik?{'idempotency-key':ik}:{})},body:JSON.stringify({name:f.get('name'),payload,priority:Number(f.get('priority'))})});setNotice(`${r.duplicate?'Existing event returned':'Event accepted'}: ${r.jobId}`);setModal('');});}}><h2>Send an event</h2><p>Use an API key belonging to the selected project.</p><label>API key<input name="key" type="password" required autoComplete="off"/></label><label>Event name<input name="name" defaultValue="order.created" required/></label><label>Payload (JSON object)<textarea name="payload" defaultValue={'{\n  "orderId": "123"\n}'} rows={4}/></label><div className="form-row"><label>Priority (10 is highest)<input name="priority" type="number" min={1} max={10} defaultValue={5}/></label><label>Idempotency key<input name="idempotency" placeholder="Optional"/></label></div><button className="primary" disabled={busy}>Queue event</button></form>}
  {modal === 'detail' && detail && <><h2>{detail.name}</h2><code>{detail._id}</code><div className="detail-state"><Status value={detail.status}/><span>{detail.attempts} total attempts · replay {detail.generation}</span></div><pre>{JSON.stringify(detail.payload,null,2)}</pre>{detail.error && <div className="error"><b>{detail.error.code}</b><p>{detail.error.message}</p></div>}<div className="form-row"><button className="primary" disabled={busy||detail.status!=='dead-letter'} onClick={()=>void action(async()=>{await api(`/projects/${selected}/jobs/${detail._id}/retry`,{method:'POST'});setModal('');setNotice('Job queued for replay.');})}>Retry job</button><button disabled={busy||!detail.error} onClick={()=>void action(async()=>{const r=await api<{label:string;explanation:string}>(`/projects/${selected}/jobs/${detail._id}/explain`,{method:'POST'});setSuggestion(`${r.label}\n\n${r.explanation}`);})}>Explain failure</button></div>{suggestion && <pre className="suggestion">{suggestion}</pre>}</>}
  </Dialog></div>}</div>;
}
function Dialog({ children, label, close }: { children: React.ReactNode; label: string; close: () => void }) {
  const ref = useRef<HTMLElement>(null);
  const closeRef = useRef(close); closeRef.current = close;
  useEffect(() => {
    const prior = document.activeElement as HTMLElement | null;
    const root = ref.current!;
    const focusable = () => Array.from(root.querySelectorAll<HTMLElement>('button:not(:disabled), input, textarea, select, [tabindex="0"]'));
    (root.querySelector<HTMLElement>('input') || focusable()[0] || root).focus();
    const keyboard = (e: KeyboardEvent) => {
      if (e.key === 'Escape') closeRef.current();
      if (e.key !== 'Tab') return;
      const items = focusable(), first = items[0], last = items[items.length - 1];
      if (!first) { e.preventDefault(); root.focus(); }
      else if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
      else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
    };
    root.addEventListener('keydown', keyboard);
    return () => { root.removeEventListener('keydown', keyboard); prior?.focus(); };
  }, []);
  return <section ref={ref} className="dialog" role="dialog" aria-modal="true" aria-label={label} tabIndex={-1}>{children}</section>;
}
function Status({value}:{value:string}) { return <span className={`status ${value}`}><i/>{statusLabel(value)}</span>; }
createRoot(document.getElementById('root')!).render(<App/>);
